"""
Hotel delay notification service.
Generates a realistic notification email and sends it to DEMO_EMAIL.
All outgoing hotel emails are redirected to the demo mailbox — no real
hotel businesses are ever contacted.

Production path: replace _send_smtp with a Celery task → SendGrid/SES.
"""
import logging
import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)

DEMO_EMAIL    = os.getenv("DEMO_EMAIL", "")
SMTP_HOST     = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT     = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER     = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")


def _send_smtp(to_addr: str, subject: str, body: str) -> bool:
    """Send email via SMTP, always redirecting to DEMO_EMAIL."""
    if not all([DEMO_EMAIL, SMTP_USER, SMTP_PASSWORD]):
        logger.info(
            "SMTP not configured — skipping send (set DEMO_EMAIL, SMTP_USER, SMTP_PASSWORD). "
            "Email would have gone to: %s | Subject: %s",
            to_addr, subject,
        )
        return False
    msg = MIMEMultipart()
    msg["From"]               = SMTP_USER
    msg["To"]                 = DEMO_EMAIL
    msg["Subject"]            = subject
    msg["X-Original-Recipient"] = to_addr  # shows intended hotel in headers
    msg.attach(MIMEText(body, "plain"))
    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.send_message(msg)
        logger.info("HOTEL_NOTIFY | email sent → %s (demo mailbox for %s)", DEMO_EMAIL, to_addr)
        return True
    except Exception as exc:
        logger.error("HOTEL_NOTIFY | SMTP send failed: %s", exc)
        return False


def notify_hotel_of_delay(
    hotel_name: str,
    booking_reference: str,
    original_checkin: str,
    new_estimated_arrival: str,
    delay_minutes: int,
    guest_name: str = "Guest",
    hotel_email: str = "reservations@hotel.demo",
) -> dict:
    """
    Generate and send a hotel late-arrival notification.

    The email is always sent to DEMO_EMAIL (never to a real hotel).
    The body clearly states it is a simulated notification.
    """
    subject = f"[SIMULATED] Late arrival notice — booking {booking_reference}"
    body = (
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "  SIMULATED HOTEL NOTIFICATION\n"
        "  Generated by ReRoute AI — Portfolio Demo\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
        f"This email demonstrates the notification that would be sent\n"
        f"to {hotel_name} in a production deployment.\n\n"
        f"Hotel:            {hotel_name}\n"
        f"Intended address: {hotel_email}\n"
        f"Guest:            {guest_name}\n"
        f"Booking ref:      {booking_reference}\n\n"
        f"Flight delay:     {delay_minutes} minutes\n"
        f"Original check-in:{original_checkin}\n"
        f"Updated arrival:  {new_estimated_arrival}\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "Original message that would be sent:\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
        f"Dear {hotel_name} team,\n\n"
        f"This is an automated notification from ReRoute AI.\n\n"
        f"Guest {guest_name} (booking ref: {booking_reference}) is experiencing a flight\n"
        f"delay of approximately {delay_minutes} minutes. Their original check-in was\n"
        f"scheduled for {original_checkin}; estimated arrival is now {new_estimated_arrival}.\n\n"
        f"Please hold the reservation and ensure late check-in access.\n\n"
        f"— ReRoute AI Automated Notification System"
    )

    logger.info(
        "HOTEL_NOTIFY | hotel=%s ref=%s delay=%dmin new_arrival=%s",
        hotel_name, booking_reference, delay_minutes, new_estimated_arrival,
    )

    sent = _send_smtp(hotel_email, subject, body)

    return {
        "hotel_notified":       True,
        "booking_reference":    booking_reference,
        "notification_sent_at": datetime.utcnow().isoformat(),
        "channel":              "email_sent" if sent else "email_simulated",
        "subject":              subject,
        "status":               f"Hotel notified of late arrival — new ETA {new_estimated_arrival}",
        "email_delivered":      sent,
    }
